#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-MooseX-Role-WithOverloading
Version  : 0.17
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/MooseX-Role-WithOverloading-0.17.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/MooseX-Role-WithOverloading-0.17.tar.gz
Summary  : '(DEPRECATED) Roles which support overloading'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-MooseX-Role-WithOverloading-lib
BuildRequires : buildreq-cpan
BuildRequires : perl(Moose)
BuildRequires : perl(Moose::Exporter)
BuildRequires : perl(Moose::Role)
BuildRequires : perl(aliased)
BuildRequires : perl(namespace::autoclean)
BuildRequires : perl(namespace::clean)

%description
This archive contains the distribution MooseX-Role-WithOverloading,
version 0.17:

%package dev
Summary: dev components for the perl-MooseX-Role-WithOverloading package.
Group: Development
Requires: perl-MooseX-Role-WithOverloading-lib
Provides: perl-MooseX-Role-WithOverloading-devel

%description dev
dev components for the perl-MooseX-Role-WithOverloading package.


%package doc
Summary: doc components for the perl-MooseX-Role-WithOverloading package.
Group: Documentation

%description doc
doc components for the perl-MooseX-Role-WithOverloading package.


%package lib
Summary: lib components for the perl-MooseX-Role-WithOverloading package.
Group: Libraries

%description lib
lib components for the perl-MooseX-Role-WithOverloading package.


%prep
%setup -q -n MooseX-Role-WithOverloading-0.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-MooseX-Role-WithOverloading
cp LICENCE %{buildroot}/usr/share/doc/perl-MooseX-Role-WithOverloading/LICENCE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/Composite.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/Composite/ToClass.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/Composite/ToInstance.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/Composite/ToRole.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/FixOverloadedRefs.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/ToClass.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/ToInstance.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Application/ToRole.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/MooseX/Role/WithOverloading/Meta/Role/Composite.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/MooseX::Role::WithOverloading.3
/usr/share/man/man3/MooseX::Role::WithOverloading::Meta::Role::Application.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/perl\-MooseX\-Role\-WithOverloading/*

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/MooseX/Role/WithOverloading/WithOverloading.so
